version: '3'
services:
  langchain-chat-app:
    image: dlai-hf-course:latest
    build: ./app
    command: jupyter lab --port 8888
    volumes:
      - ./notebooks/:/app/notebooks
    ports:
      - 8888:8888
