version: '3'
services:
  langchain-chat-app:
    image: dlai-hf-course:latest
    env_file:
    - .env
    build: ./app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root 
    volumes:
      - ./notebooks/: /app/notebooks
    ports:
      - 8888:8888
