version: '3'
services:
  langchain-chat-app:
    image: dlai-hf-course:latest
    build: ./app
    command: jupyter lab --port 8080
    volumes:
      - ./notebooks/:/app/notebooks
    ports:
      - 8080:8080
